# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Artifact Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run Gradle command
      uses: Raul6469/android-gradle-action@2.0.0
      with:
        # The gradle command you wish to run (required)
        # Here, `./gradlew test` will be run
        script: assembleDebug
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: pull-request-build
        path: "*/*/build/outputs/apk/*.apk"
